-- ================================================================
-- WUCC eVoting Seed Data
--
-- Setup order:
--   1. Run supabase/reset_wucc_evoting.sql
--   2. Run this file: supabase/seed.sql
--   3. Create Supabase Auth users for admins as needed
--   4. Insert matching public.profiles rows for admin users
--
-- This seed is intentionally self-contained and uses only the current
-- election statuses: inactive, standby, active, ended, finalized.
-- Password hashes for seeded voters are generated by the voters table
-- trigger in reset_wucc_evoting.sql. That trigger uses schema-safe
-- pgcrypto wrappers and `gen_salt('md5')` for academic/demo stability,
-- so default voter passwords remain each voter's matric number.
-- ================================================================

begin;

create extension if not exists pgcrypto;

do $$
begin
  if to_regclass('public.elections') is null
    or to_regclass('public.positions') is null
    or to_regclass('public.voters') is null
    or to_regclass('public.candidate_applications') is null
    or to_regclass('public.candidates') is null
    or to_regclass('public.blocks') is null
    or to_regclass('public.ballots') is null
    or to_regclass('public.votes') is null
    or to_regclass('public.audit_logs') is null
    or to_regprocedure('public.pgcrypto_crypt(text,text)') is null
    or to_regprocedure('public.pgcrypto_gen_salt(text)') is null
    or to_regprocedure('public.pgcrypto_random_bytes(integer)') is null
    or to_regprocedure('public.pgcrypto_random_uuid()') is null
    or to_regprocedure('public.pgcrypto_digest(text,text)') is null
    or to_regprocedure('public.get_candidate_results_safe()') is null
    or to_regprocedure('public.get_election_stats_safe()') is null
    or to_regprocedure('public.get_public_receipts_safe()') is null
    or to_regprocedure('public.get_voter_ballot_status_safe(uuid,uuid)') is null
    or to_regprocedure('public.register_voter(text,text,text,text,text,uuid)') is null
    or to_regprocedure('public.check_voter_duplicate(text,text,uuid)') is null
    or to_regprocedure('public.check_candidate_application_duplicate(uuid,uuid,text,text)') is null
    or to_regprocedure('public.get_voter_login_by_email(text)') is null
    or to_regprocedure('public.verify_voter_password(text,text)') is null
    or to_regprocedure('public.change_voter_password(uuid,text,text)') is null
    or to_regprocedure('public.cast_ballot(text,text,text,jsonb)') is null
    or to_regprocedure('public.update_current_election_settings(text,text,timestamptz,timestamptz)') is null
    or to_regprocedure('public.reset_current_election_data()') is null
    or to_regprocedure('public.delete_voter(uuid)') is null
    or to_regprocedure('public.delete_candidate(uuid)') is null
    or to_regprocedure('public.delete_candidate_application(uuid)') is null
  then
    raise exception 'Run supabase/reset_wucc_evoting.sql before seed.sql.';
  end if;
end $$;

-- Election ---------------------------------------------------------

insert into public.elections (title, status, ledger_status, starts_at, ends_at)
select 'WUCC', 'standby'::public.election_status, 'open', now() + interval '15 minutes', now() + interval '8 hours'
where not exists (select 1 from public.elections);

update public.elections e
set title = 'WUCC',
    status = case
      when e.status::text in ('inactive', 'standby', 'active', 'ended', 'finalized') then e.status
      else 'standby'::public.election_status
    end,
    ledger_status = case
      when e.status::text = 'finalized' then 'finalized'
      when e.status::text = 'ended' then 'ready_to_finalize'
      when e.status::text = 'inactive' then 'locked'
      else 'open'
    end,
    starts_at = coalesce(e.starts_at, now() + interval '15 minutes'),
    ends_at = coalesce(e.ends_at, now() + interval '8 hours'),
    updated_at = now()
where e.id = (select latest_election.id from public.elections latest_election order by latest_election.created_at desc limit 1);

-- Positions --------------------------------------------------------

with current_election as (
  select e.id from public.elections e order by e.created_at desc limit 1
),
canonical(slug, title, icon, display_order) as (
  values
    ('governor', 'Governor', 'shield', 1),
    ('deputy-governor', 'Deputy Governor', 'medal', 2),
    ('gsec', 'General Secretary', 'clipboard', 3),
    ('agsec', 'Assistant General Secretary', 'file-text', 4),
    ('fsec', 'Financial Secretary', 'wallet', 5),
    ('pro', 'Public Relations Officer', 'megaphone', 6),
    ('dwelfare', 'Director of Welfare', 'heart-handshake', 7),
    ('dhealth', 'Director of Health', 'cross', 8),
    ('dsport', 'Director of Sports', 'trophy', 9),
    ('dsocials', 'Director of Socials', 'sparkles', 10)
)
insert into public.positions (election_id, slug, title, icon, display_order, is_active)
select current_election.id, canonical.slug, canonical.title, canonical.icon, canonical.display_order, true
from current_election
cross join canonical
on conflict (election_id, slug) do update set
  title = excluded.title,
  icon = excluded.icon,
  display_order = excluded.display_order,
  is_active = true,
  updated_at = now();

-- Voters -----------------------------------------------------------

with demo_voters(full_name, matric, department, level, email, status, has_voted) as (
  values
    ('Emeka Okafor', 'COSC/21045', 'Computer Science', '300L', 'emeka@votechain.local', 'approved'::public.record_status, true),
    ('Blessing Adeyemi', 'CYB/21007', 'Cybersecurity', '400L', 'blessing@votechain.local', 'approved'::public.record_status, true),
    ('Tunde Bakare', 'IT/20445', 'Information Technology', '400L', 'tunde@votechain.local', 'approved'::public.record_status, false),
    ('Nora Etim', 'COSC/22031', 'Computer Science', '200L', 'nora@votechain.local', 'approved'::public.record_status, false),
    ('Ifeoma Nwosu', 'COSC/21334', 'Computer Science', '300L', 'ifeoma@votechain.local', 'pending'::public.record_status, false),
    ('Amina Yusuf', 'SWE/22018', 'Software Engineering', '200L', 'amina@votechain.local', 'pending'::public.record_status, false),
    ('Kelvin Musa', 'SWE/21028', 'Software Engineering', '300L', 'kelvin@votechain.local', 'rejected'::public.record_status, false)
)
insert into public.voters (full_name, matric, department, level, email, status, has_voted)
select full_name, upper(matric), department, level, lower(email), status, has_voted
from demo_voters
on conflict (matric) do update set
  full_name = excluded.full_name,
  department = excluded.department,
  level = excluded.level,
  email = excluded.email,
  password_hash = public.pgcrypto_crypt(upper(excluded.matric), public.pgcrypto_gen_salt('md5')),
  password_changed_at = null,
  status = excluded.status,
  has_voted = excluded.has_voted,
  updated_at = now();

-- Candidate applications -----------------------------------------

with current_election as (
  select e.id from public.elections e order by e.created_at desc limit 1
),
apps(slug, full_name, matric, department, level, email, phone, cgpa, manifesto, promises, previous_role, status, reference) as (
  values
    ('governor', 'Emeka Okafor', 'COSC/21045', 'Computer Science', '300L', 'emeka@votechain.local', '08010000001', 4.42, 'Build a transparent, digital-first WUCC administration.', array['Transparent reports', 'Student tech hub', 'Digital support desk']::text[], 'Class representative', 'approved'::public.record_status, 'WUCC-APP-GOV-001'),
    ('governor', 'Chidinma Eze', 'COSC/20312', 'Computer Science', '400L', 'chidinma@votechain.local', '08010000002', 4.68, 'Improve welfare, transparency, and student inclusion.', array['Quarterly reports', 'Welfare packages', 'Women in Tech fund']::text[], 'Tech club lead', 'approved'::public.record_status, 'WUCC-APP-GOV-002'),
    ('deputy-governor', 'Blessing Adeyemi', 'CYB/21007', 'Cybersecurity', '400L', 'blessing@votechain.local', '08010000003', 4.51, 'Support student safety, wellness, and secure digital culture.', array['Mental health desk', 'Cyber awareness', 'Welfare fund']::text[], 'Department assistant rep', 'approved'::public.record_status, 'WUCC-APP-DGOV-001'),
    ('deputy-governor', 'Tunde Bakare', 'IT/20445', 'Information Technology', '400L', 'tunde@votechain.local', '08010000004', 4.20, 'Connect students to projects, internships, and industry.', array['Project funding', 'Industry linkages', 'Internship portal']::text[], 'Project coordinator', 'approved'::public.record_status, 'WUCC-APP-DGOV-002'),
    ('gsec', 'Ifeoma Nwosu', 'COSC/21334', 'Computer Science', '300L', 'ifeoma@votechain.local', '08010000005', 4.36, 'Make WUCC records, minutes, and communication easy to access.', array['Digital records', 'Public minutes', 'Better communication']::text[], 'Secretary, study group', 'pending'::public.record_status, 'WUCC-APP-GSEC-001'),
    ('agsec', 'Amina Yusuf', 'SWE/22018', 'Software Engineering', '200L', 'amina@votechain.local', '08010000006', 4.12, 'Support faster documentation and student communication.', array['Class rep portal', 'Notice archive', 'Fast minutes']::text[], 'Volunteer secretary', 'pending'::public.record_status, 'WUCC-APP-AGSEC-001'),
    ('pro', 'Sarah Ibekwe', 'CYB/22014', 'Cybersecurity', '200L', 'sarah@votechain.local', '08010000007', 4.31, 'Make WUCC announcements clear, timely, and accessible.', array['Better publicity', 'Event calendar', 'Student feedback']::text[], 'Media volunteer', 'rejected'::public.record_status, 'WUCC-APP-PRO-001')
)
insert into public.candidate_applications (
  election_id,
  position_id,
  full_name,
  matric,
  department,
  level,
  email,
  phone,
  manifesto,
  promises,
  cgpa,
  previous_role,
  status,
  reference,
  photo_url
)
select
  current_election.id,
  p.id,
  apps.full_name,
  upper(apps.matric),
  apps.department,
  apps.level,
  lower(apps.email),
  apps.phone,
  apps.manifesto,
  apps.promises,
  apps.cgpa,
  apps.previous_role,
  apps.status,
  apps.reference,
  null
from apps
join current_election on true
join public.positions p on p.election_id = current_election.id and p.slug = apps.slug
on conflict (election_id, position_id, matric) do update set
  full_name = excluded.full_name,
  department = excluded.department,
  level = excluded.level,
  email = excluded.email,
  phone = excluded.phone,
  manifesto = excluded.manifesto,
  promises = excluded.promises,
  cgpa = excluded.cgpa,
  previous_role = excluded.previous_role,
  status = excluded.status,
  reference = excluded.reference,
  updated_at = now();

-- Approved application candidates --------------------------------

insert into public.candidates (
  election_id,
  position_id,
  application_id,
  full_name,
  matric,
  email,
  department,
  level,
  cgpa,
  manifesto,
  promises,
  photo_url,
  status
)
select
  app.election_id,
  app.position_id,
  app.id,
  app.full_name,
  app.matric,
  app.email,
  app.department,
  app.level,
  app.cgpa,
  app.manifesto,
  app.promises,
  app.photo_url,
  'approved'
from public.candidate_applications app
where app.status = 'approved'
on conflict (election_id, position_id, matric) do update set
  application_id = excluded.application_id,
  full_name = excluded.full_name,
  email = excluded.email,
  department = excluded.department,
  level = excluded.level,
  cgpa = excluded.cgpa,
  manifesto = excluded.manifesto,
  promises = excluded.promises,
  photo_url = excluded.photo_url,
  status = 'approved',
  updated_at = now();

-- Manual/seed-only candidates ensure every office is visible in admin
-- and Vote/Results have approved ballot options after a fresh install.

with current_election as (
  select e.id from public.elections e order by e.created_at desc limit 1
),
manual_candidates(slug, full_name, matric, email, department, level, cgpa, manifesto, promises, avatar) as (
  values
    ('gsec', 'Daniel Iro', 'IT/21022', 'daniel@votechain.local', 'Information Technology', '300L', 4.09, 'Keep communication concise, traceable, and timely.', array['Meeting minutes', 'Academic reminders', 'Digital forms']::text[], 'avatar'),
    ('agsec', 'Mariam Bello', 'CYB/22018', 'mariam@votechain.local', 'Cybersecurity', '200L', 4.01, 'Make assistant secretarial support more responsive.', array['Notice templates', 'Class feedback', 'Document support']::text[], 'avatar'),
    ('fsec', 'David Mensah', 'IT/21119', 'david@votechain.local', 'Information Technology', '300L', 4.05, 'Keep WUCC finances accountable and easy to understand.', array['Monthly reports', 'Transparent dues', 'Budget dashboard']::text[], 'avatar'),
    ('pro', 'Sarah Ibekwe', 'CYB/22014', 'sarah@votechain.local', 'Cybersecurity', '200L', 4.31, 'Make WUCC announcements clear, timely, and accessible.', array['Better publicity', 'Event calendar', 'Student feedback']::text[], 'avatar'),
    ('dwelfare', 'Kelvin Musa', 'SWE/21028', 'kelvin@votechain.local', 'Software Engineering', '300L', 4.18, 'Prioritize student welfare and responsive support.', array['Welfare desk', 'Emergency support', 'Peer mentoring']::text[], 'avatar'),
    ('dhealth', 'Nora Etim', 'COSC/22031', 'nora@votechain.local', 'Computer Science', '200L', 4.27, 'Promote health awareness and campus wellness.', array['Health drives', 'Wellness talks', 'First-aid readiness']::text[], 'avatar'),
    ('dsport', 'Michael Obi', 'IT/22042', 'michael@votechain.local', 'Information Technology', '200L', 3.91, 'Build a stronger WUCC sports culture.', array['Inter-level games', 'Training schedules', 'Sports equipment']::text[], 'avatar'),
    ('dsocials', 'Grace Danjuma', 'CYB/21033', 'grace@votechain.local', 'Cybersecurity', '300L', 4.08, 'Create memorable social events for all WUCC students.', array['Inclusive events', 'Talent night', 'Freshers welcome']::text[], 'avatar')
)
insert into public.candidates (
  election_id,
  position_id,
  full_name,
  matric,
  email,
  department,
  level,
  cgpa,
  manifesto,
  promises,
  avatar,
  status
)
select
  current_election.id,
  p.id,
  c.full_name,
  upper(c.matric),
  lower(c.email),
  c.department,
  c.level,
  c.cgpa,
  c.manifesto,
  c.promises,
  c.avatar,
  'approved'
from manual_candidates c
join current_election on true
join public.positions p on p.election_id = current_election.id and p.slug = c.slug
on conflict (election_id, position_id, matric) do update set
  full_name = excluded.full_name,
  email = excluded.email,
  department = excluded.department,
  level = excluded.level,
  cgpa = excluded.cgpa,
  manifesto = excluded.manifesto,
  promises = excluded.promises,
  avatar = excluded.avatar,
  status = 'approved',
  updated_at = now();

-- Demo blockchain ledger -----------------------------------------
-- Two deterministic PBFT-confirmed demo ballots. They use hashes only
-- in public ledger views; voter identity remains private behind RLS/RPC.

with current_election as (
  select e.id from public.elections e order by e.created_at desc limit 1
),
demo_ballots(matric, block_number, tx_hash, vote_hash, receipt_hash, block_hash, voter_hash, previous_hash) as (
  values
    ('COSC/21045', 1201::bigint, '0xseedtx000000000000000000000000000000000000000000000000000000000001', '0xseedvote000000000000000000000000000000000000000000000000000000001', '0xseedreceipt000000000000000000000000000000000000000000000000000001', '0xseedblock000000000000000000000000000000000000000000000000000001', '0xseedvoter000001', null::text),
    ('CYB/21007', 1202::bigint, '0xseedtx000000000000000000000000000000000000000000000000000000000002', '0xseedvote000000000000000000000000000000000000000000000000000000002', '0xseedreceipt000000000000000000000000000000000000000000000000000002', '0xseedblock000000000000000000000000000000000000000000000000000002', '0xseedvoter000002', '0xseedblock000000000000000000000000000000000000000000000000000001')
),
inserted_blocks as (
  insert into public.blocks (
    election_id,
    voter_id,
    block_number,
    tx_hash,
    vote_hash,
    receipt_hash,
    block_hash,
    voter_hash,
    previous_hash,
    validator_status,
    validation_status,
    consensus_status,
    validator_confirmations,
    confirmation_count
  )
  select
    current_election.id,
    v.id,
    demo_ballots.block_number,
    demo_ballots.tx_hash,
    demo_ballots.vote_hash,
    demo_ballots.receipt_hash,
    demo_ballots.block_hash,
    demo_ballots.voter_hash,
    demo_ballots.previous_hash,
    'pbft_confirmed',
    'pbft_confirmed',
    'confirmed',
    4,
    4
  from demo_ballots
  join current_election on true
  join public.voters v on upper(v.matric) = upper(demo_ballots.matric)
  on conflict (tx_hash) do update set
    vote_hash = excluded.vote_hash,
    receipt_hash = excluded.receipt_hash,
    block_hash = excluded.block_hash,
    validation_status = 'pbft_confirmed',
    consensus_status = 'confirmed'
  returning id, election_id, voter_id, block_number, tx_hash, vote_hash, receipt_hash, block_hash, previous_hash, voter_hash, validation_status, created_at
),
inserted_ballots as (
  insert into public.ballots (
    election_id,
    voter_id,
    block_id,
    block_number,
    tx_hash,
    vote_hash,
    receipt_hash,
    block_hash,
    previous_hash,
    voter_hash,
    validator_status,
    validation_status,
    consensus_status,
    validator_confirmations,
    confirmation_count
  )
  select
    election_id,
    voter_id,
    id,
    block_number,
    tx_hash,
    vote_hash,
    receipt_hash,
    block_hash,
    previous_hash,
    voter_hash,
    'pbft_confirmed',
    'pbft_confirmed',
    'confirmed',
    4,
    4
  from inserted_blocks
  on conflict (tx_hash) do update set
    vote_hash = excluded.vote_hash,
    receipt_hash = excluded.receipt_hash,
    block_hash = excluded.block_hash,
    validation_status = 'pbft_confirmed',
    consensus_status = 'confirmed'
  returning id, election_id, voter_id, block_id, receipt_hash, block_hash
),
first_candidates as (
  select distinct on (c.election_id, c.position_id)
    c.election_id,
    c.position_id,
    c.id as candidate_id
  from public.candidates c
  where c.status = 'approved'
  order by c.election_id, c.position_id, c.created_at asc
)
insert into public.votes (
  election_id,
  ballot_id,
  block_id,
  voter_id,
  position_id,
  candidate_id,
  vote_hash,
  receipt_hash,
  block_hash,
  validation_status,
  consensus_status
)
select
  b.election_id,
  b.id,
  b.block_id,
  b.voter_id,
  fc.position_id,
  fc.candidate_id,
  '0x' || encode(public.pgcrypto_digest(b.receipt_hash || ':' || fc.position_id::text || ':' || fc.candidate_id::text, 'sha256'), 'hex'),
  b.receipt_hash,
  b.block_hash,
  'pbft_confirmed',
  'confirmed'
from inserted_ballots b
join first_candidates fc on fc.election_id = b.election_id
on conflict (election_id, voter_id, position_id) do update set
  candidate_id = excluded.candidate_id,
  vote_hash = excluded.vote_hash,
  receipt_hash = excluded.receipt_hash,
  block_hash = excluded.block_hash,
  validation_status = 'pbft_confirmed',
  consensus_status = 'confirmed';

update public.voters v
set has_voted = true,
    updated_at = now()
where upper(v.matric) in ('COSC/21045', 'CYB/21007');

commit;
